// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnoITlROb5tqHKTMk6eOSwtSw6r9sGLWc',
    appId: '1:962718643509:web:20568abad68ded03f8087c',
    messagingSenderId: '962718643509',
    projectId: 'getconnect-project-9b7d7',
    authDomain: 'getconnect-project-9b7d7.firebaseapp.com',
    databaseURL: 'https://getconnect-project-9b7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'getconnect-project-9b7d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAwBMO-ykrJhQeMY_cEARIh9BEZIq8STg',
    appId: '1:962718643509:android:d5c55f5060a19219f8087c',
    messagingSenderId: '962718643509',
    projectId: 'getconnect-project-9b7d7',
    databaseURL: 'https://getconnect-project-9b7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'getconnect-project-9b7d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hyUawaAyH3ziT8Y8S6NMKRQnp9hdAHU',
    appId: '1:962718643509:ios:072b379e9e50b914f8087c',
    messagingSenderId: '962718643509',
    projectId: 'getconnect-project-9b7d7',
    databaseURL: 'https://getconnect-project-9b7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'getconnect-project-9b7d7.appspot.com',
    iosBundleId: 'com.example.mybidan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnoITlROb5tqHKTMk6eOSwtSw6r9sGLWc',
    appId: '1:962718643509:web:d1c62c4111dc3c2bf8087c',
    messagingSenderId: '962718643509',
    projectId: 'getconnect-project-9b7d7',
    authDomain: 'getconnect-project-9b7d7.firebaseapp.com',
    databaseURL: 'https://getconnect-project-9b7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'getconnect-project-9b7d7.appspot.com',
  );
}
